### ISSUE TITLE
java.lang.RuntimeException: An error occurred while executing doInBackground()

### ISSUE THREAD

**Issue by jgaut** [jgaut/IntercomThing#1]
```bash
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:318)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.RuntimeException: javax.mail.MessagingException: Unknown SMTP host: smtp.gmail.com;
  nested exception is:
	java.net.UnknownHostException: smtp.gmail.com
	at com.example.jeremy.intercomthing.MyEmail.sendEmail(MyEmail.java:65)
	at com.example.jeremy.intercomthing.MyEmail.doInBackground(MyEmail.java:72)
	at com.example.jeremy.intercomthing.MyEmail.doInBackground(MyEmail.java:21)
	at android.os.AsyncTask$2.call(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
Caused by: javax.mail.MessagingException: Unknown SMTP host: smtp.gmail.com;
  nested exception is:
	java.net.UnknownHostException: smtp.gmail.com
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1389)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:412)
	at javax.mail.Service.connect(Service.java:310)
	at javax.mail.Service.connect(Service.java:169)
	at javax.mail.Service.connect(Service.java:118)
	at javax.mail.Transport.send0(Transport.java:188)
	at javax.mail.Transport.send(Transport.java:118)
	at com.example.jeremy.intercomthing.MyEmail.sendEmail(MyEmail.java:60)
	... 8 more
Caused by: java.net.UnknownHostException: smtp.gmail.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:174)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
	at java.net.Socket.connect(Socket.java:586)
	at java.net.Socket.connect(Socket.java:535)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:233)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:189)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1359)
	... 15 more

```

**Comment by jgaut** [comment]
C'est OK.
